name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.11'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v5

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install-deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: run-flake8
        run: flake8 .

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v5

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install-repo
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-subtests pytest-cov
          pip install --verbose .

      - name: run-pytest
        run: pytest --cov=bblean --cov-report=json -s -k 'not regression' ./tests

      - name: upload-badge-artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.json

  upload-coverage-badge:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: create-site-dir
        run: mkdir -p site/coverage

      - name: fetch-coverage-report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: ./site/coverage/

      - name: generate-coverage-badge
        run: |
          COVERAGE=$(jq '.totals.percent_covered_display' site/coverage/coverage.json)
          echo "{\"schemaVersion\":1,\"label\":\"coverage\",\"message\":\"${COVERAGE}%\",\"color\":\"green\"}" > site/coverage/coverage-badge.json

      - name: deploy-badge
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages

  # Ubuntu 24.04 for reproducibility in regression tests only
  # coverage makes tests slightly slower, so regression tests should not run with
  # coverage
  regression-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout-repo
        uses: actions/checkout@v5

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install-repo
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-subtests
          pip install --verbose .

      - name: run-pytest
        run: pytest -s ./tests/test_regression.py
